### ISSUE TITLE
Google Translate App is broken

### ISSUE THREAD

**Issue by fdhfgbsjedfg-775** [ph00lt0/blocklist#3]
This issue is caused by the api domain being blocked (translate-pa.googleapis.com), this domain is responsible for core functions of Google Translate,

Originating rule:- ||*-pa.googleapis.com^

Device: Samsung S20 FE 5G
Browser: *none* (Used the Google Translate app for this)
Blocklist: https://raw.githubusercontent.com/ph00lt0/blocklists/master/blocklist.txt (AdGuard syntax)

**Comment by fdhfgbsjedfg-775** [comment]
From what I can tell, translate-pa.googleapis.com is not a tracker nor advertisement domain, I tested it 19 blocklists (1Hosts Lite, ABPVN, AD-WARS, AdAway, AdGuard DNS Filters, Anti-AD, Anudeep's blocklist, Disconnect {Ads}, Easylist, Easyprivacy, Easylist China, Energized Blu & Blu Go, HostsVN

**Comment by ph00lt0** [comment]
@fdhfgbsjedfg-775 hey man I tried to figure out how you added the list in Adguard. Could you please provide the details of how you have done so? Are using the content filtering app or vpn app?

**Comment by fdhfgbsjedfg-775** [comment]
To specify which app, it's the with the one with the  local VPN tunnel (source: https://adguard.com/adguard-android/overview.html), to add filter lists,
Open AdGuard > click on the icon on top left > click on settings > click on content blocking > go to Filters > go to custom filters > click on *+new custom filter* > input blocklist link on *URL or path* then click on import > *optional* tick on trusted filters *optional* > click *Add* > You're done!, or for users convenience put a subscription script on you're README.MD file that users can one click to subscribe (script: abp:subscribe?location=https%3A%2F%2Fexample.com%2Fuser%2F.example-file%2Fmaster%2Fhosts.txt&title=your-title-here

**Comment by ph00lt0** [comment]
thanks man, I did not know about this app as it isn't in any store. Will have a try!
