### ISSUE TITLE
gllto.glpals.com is used for A-GPS

### ISSUE THREAD

**Issue by yoshimo** [ph00lt0/blocklist#38]
**Tool used (pick one)**:
 - [ ] uBlock Origin
 - [ ] Adguard for iOS
 - [ ] Adguard for Android
 - [ ] Adguard Browser add-on/extension
 - [ ] Brave Ad Block
 - [x] PiHole
 - [ ] Adguard Home

[comment]: <> (Change one of the boxes to - [x] to "select" it.)

**What service are you trying to use?'**
GPS on a Samsung device

**What does not work?**
Assisted-GPS falls back to satellite only and takes longer.

**Which rule you believe is causing this?**
`gllto.glpals.com`

**Comment by JanOstrowka** [comment]
gllto.glpals.com has been delisted
thank you @yoshimo for feedback
